version: "3.7"
services:
  e_wallet:
    image: e-wallet:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
  react_ui:
    image: e-wallet-react-ui:latest
    restart: always
    ports:
      - 3000:3000